[Colmap]
matcher = "exhaustive"
compute_dense = true

[Colmap.cli_args.feature_extractor]
"--ImageReader.single_camera" = "1"
"--ImageReader.camera_model" = "SIMPLE_RADIAL"
"--ImageReader.camera_params" = "1379.78039550781, 978.726440429688, 529.610412597656, 0"

[Colmap.cli_args.mapper]
"--Mapper.ba_refine_focal_length" = "false"
"--Mapper.ba_refine_principal_point" = "false"
"--Mapper.ba_refine_extra_params" = "false"
"--Mapper.ba_global_use_pba" = "false"

[Colmap.cli_args.model_aligner]
"--robust_alignment_max_error" = "10"

[Visualization]
max_image_size = 1500
max_pcd_size = 100000
thumbnail_size = 150

pcd_source = "colmap_dense"
