[Colmap]
matcher = "exhaustive"
compute_dense = false

[Colmap.cli_args.feature_extractor]
"--ImageReader.single_camera" = "1"
"--SiftExtraction.use_gpu" = "1"

[Colmap.cli_args.exhaustive_matcher]
"--SiftMatching.use_gpu" = "1"

[Colmap.cli_args.model_aligner]
"--robust_alignment_max_error" = "10"

[Masking]
type = "linear"

[Masking.params]
dilation = 5
coefs = [0.0, 1.0, 0.0, 0.3]

[SoftMasking]
type = "vesselness"

[SoftMasking.params]
scale = 4

[SpaceCarving]
voxel_size = 1.0

[Voxel2PointCloud]
dist = 1.0

[Animate]
rot_speed_x = 10.0
rot_speed_y = 10.0
n_img = 100

[Visualization]
max_image_size = 1500
max_pcd_size = 10000
thumbnail_size = 150
pcd_source = "vox2pcd"
mesh_source = "delaunay"
