[accessory]
calibration_scan_id = "calib_scan_shortpath"

[Masks]
type = "excess_green"
dilation = 5
binarize = true
threshold = 0.0

[TrainingDirectory]
path = "/home/alienor/Documents/training2D/" #replace by path to your database
directory_weights = "weights/"
tsboard = "board/"
directory_dataset = "data/dataset_stem_green/"

[Segmentation2D]
upstream_task = "Scan"
query = "{\"channel\":\"rgb\"}"
labels = "background,flower,peduncle,stem,bud,leaf,fruit"
model_name = "Resnet101"
model_segmentation_name = "Resnet101_896_896_epoch51.pt"
#directory_weights = "/home/alienor/Documents/training2D/weights/"
Sx = 896
Sy = 896
epochs = 5
batch = 1
learning_rate = 0.0001

[Finetune]
directory_images = "/run/user/1001/gvfs/sftp:host=db.romi-project.eu/data/finetune/"
finetune_epochs = 10
batch = 1
train_or_scan = "scan"

[Reconstruction3D]
N_vox = 1000000
coord_file_loc = "volume/"

[Voxels]
upstream_mask = "Segmentation2D"
multiclass = true
voxel_size = 0.2
type = "averaging"
use_colmap_poses = "False"

[PointCloud]
level_set_value = 1.0

[Visualization]
max_image_size = 1500
max_pcd_size = 10000
thumbnail_size = 150
pcd_source = "vox2pcd"
mesh_source = "delaunay"
