[accessory]
calibration_scan_id = "calib_scan_shortpath"

[Masks]
upstream_task="Scan"
type = "excess_green"
dilation = 5
binarize = true
threshold = 0.0

[Segmentation2D]
upstream_task="Scan"
Sx = 256
Sy = 256
N_vox = 1000000
label_names="background,class_0,class_1,class_2,class_3,class_4"
model_segmentation_name = "table1_test5_hdri_arabidopsis_resnet50_epoch15_rotate_True_finetune_3_epoch50.pt"

#"resnet18_256_256_epoch100.pt"
# directory_images = "/home/alienor/Documents/database/FINETUNE"
directory_weights = "/home/alienor/Documents/training2D/weights/"
#"/home/twintz/.cache/romiscan"
finetune_epochs = 20

[Reconstruction3D]
N_vox = 1000000

[Voxels]
upstream_mask = "Masks"
multiclass = false
voxel_size = 0.2
type = "averaging"
#upstream_colmap = "None"
use_colmap_poses='False'

[PointCloud]
level_set_value = 1.0

[Visualization]
max_image_size = 1500
max_pcd_size = 10000
thumbnail_size = 150
pcd_source = "vox2pcd"
mesh_source = "delaunay"

#[Colmap]
#matcher = "exhaustive"
#compute_dense = false


#[Colmap.cli_args.feature_extractor]
#"--ImageReader.single_camera" = "1"
#"--SiftExtraction.use_gpu" = "1"

#[Colmap.cli_args.exhaustive_matcher]
#"--SiftMatching.use_gpu" = "1"

#[Colmap.cli_args.model_aligner]
#--robust_alignment_max_error = "10"


