[Colmap]
matcher = "exhaustive"
compute_dense = false

[accessory]
calibration_scan_id = "calib_scan_shortpath"

[Segmentation2D]
Sx = 896
Sy = 896
N_vox = 1000000
model_segmentation_name = "table1_test5_hdri_arabidopsis_resnet50_epoch15_rotate_True_finetune_3_epoch50.pt"
single_label = "background"
# directory_images = "/home/alienor/Documents/database/FINETUNE"
directory_weights = "/home/twintz/.cache/romiscan"
finetune_epochs = 20

[Masks]
upstream_task = "Segmentation2D"
type = "invert"
binarize = true
threshold = 0.01
dilation = 2

[Voxels]
multiclass = false
voxel_size = 0.7
type = "carving"

[PointCloud]
level_set_value = 1.0

[Visualization]
max_image_size = 1500
max_pcd_size = 10000
thumbnail_size = 150
pcd_source = "vox2pcd"
mesh_source = "delaunay"

[Colmap.cli_args.feature_extractor]
"--ImageReader.single_camera" = "1"
"--SiftExtraction.use_gpu" = "1"

[Colmap.cli_args.exhaustive_matcher]
"--SiftMatching.use_gpu" = "1"

[Colmap.cli_args.model_aligner]
--robust_alignment_max_error = "10"
