[Colmap]
upstream_task = "ImagesFilesetExists"

[Colmap.bounding_box]  # default to None
x = [250, 550]
y = [250, 550]
z = [-200, 150]

[Undistorted]
upstream_task = "ImagesFilesetExists"

[Masks]
upstream_task = "Undistorted"  # other option "ImagesFilesetExists"

[Voxels]
upstream_mask = "Masks"
upstream_colmap = "Colmap"

[PointCloud]
upstream_task = "Voxels"

[TriangleMesh]
upstream_task = "PointCloud"

[CurveSkeleton]
upstream_task = "TriangleMesh"

[TreeGraph]
upstream_task = "CurveSkeleton"

[AnglesAndInternodes]
upstream_task = "TreeGraph"

[Visualization]
upstream_point_cloud = "PointCloud"
upstream_mesh = "TriangleMesh"
upstream_colmap = "Colmap"
upstream_angles = "AnglesAndInternodes"
upstream_skeleton = "CurveSkeleton"
upstream_images = "ImagesFilesetExists"

[Clean]
no_confirm = true
