[Colmap]
upstream_task = "ImagesFilesetExists"
matcher = "exhaustive"
compute_dense = false
align_pcd = true
calibration_scan_id = ""

[Colmap.cli_args.feature_extractor]
"--ImageReader.single_camera" = "1" # in colmap default to 0

[Colmap.cli_args.model_aligner]
"--robust_alignment_max_error" = "10"

[Colmap.bounding_box]  # default to None
x = [250, 550]
y = [250, 550]
z = [-200, 200]

[Undistorted]
upstream_task = "ImagesFilesetExists"

[ModelFileset]
scan_id = "models"

[Segmentation2D]
upstream_task = "Undistorted"
model_fileset = "ModelFileset"
model_id = "Resnetdataset_gl_png_896_896_epoch50" # no default value
query = "{\"channel\":\"rgb\"}" # default {}
Sx = 896
Sy = 896
resize = true
binarize = true
dilation = 1
epochs = 1
batch = 1
learning_rate = 0.0001
threshold = 0.01

[Voxels]
upstream_mask = "Segmentation2D"
upstream_colmap = "Colmap"
use_colmap_poses = true
voxel_size = 1.0
type = "averaging"
log = false  # default to true
invert = false
labels = "[\"background\"]"

[PointCloud]
upstream_task = "Voxels"
level_set_value = 0.5  # default to 1.0
log = false
background_prior= 1.0
min_contrast = 10.0
min_score = 0.01  # default to 0.2

[SegmentedPointCloud]
upstream_segmentation = "Segmentation2D"
upstream_task = "PointCloud"
use_colmap_poses = true

[ClusteredMesh]
upstream_task = "SegmentedPointCloud"
min_vol = 1.0
min_length = 10.0

[AnglesAndInternodes]
upstream_task = "ClusteredMesh"
characteristic_length = 1.0
organ_type = "fruit"
stem_axis = 2
stem_axis_inverted = false
min_elongation_ratio = 2.0
min_fruit_size = 6

[Visualization]
upstream_point_cloud = "PointCloud"
upstream_mesh = "TriangleMesh"
upstream_colmap = "Colmap"
upstream_angles = "AnglesAndInternodes"
upstream_skeleton = "CurveSkeleton"
upstream_images = "ImagesFilesetExists"
max_image_size = 1500
max_point_cloud_size = 10000
thumbnail_size = 150

[Clean]
no_confirm = true
